My_Django/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path
#Template tagging
app_name='basic_app'


urlpatterns=[
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),

]

My_Django/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
    path('index2',views.index2,name='index2'),
    path('logout',views.user_logout,name='logout'),
    path('special',views.special,name='special')

]

My_Django/learning_templates/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    # additional
    portfolio_site=models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)
    def __str__(self):
        return self.user.username

My_Django/learning_templates/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo
import logging
class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

My_Django/learning_templates/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

import logging
# Create your views here.
def index(request):
    context_dict={'text':'Hello world!','number':100}
    return  render(request,'basic_app/index.html', context_dict)

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:user_login'))


def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

def index2(request):
    context_dict={'text':'Test Template!','number':100}
    return render(request,'basic_app/index2.html', context_dict)

def register(request):
    
    registered= False
    logging.error(request.method)
    if request.method == 'POST':
       user_form= UserForm(data=request.POST)
       profile_form=UserProfileInfoForm(request.POST)
       logging.error(user_form) 
       if user_form.is_valid() and profile_form.is_valid():
           user=user_form.save()
           
           user.set_password(user.password)
           user.save()

           profile=profile_form.save(commit=False)
           profile.user=user

           if 'profile_pics' in request.FILES:
            profile.profile_pic=request.FILES['profile_pics']

           profile.save()
           
           registered=True
       else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    
    return render(request,'basic_app/registeration.html',
    {'user_form':user_form,
    'profile_form':profile_form,
    'registered':registered})

def user_login(request):
    
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user = authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username:{} and password:{}".format(username,password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request,'basic_app/login.html',{})

My_Django/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  </head>
  <body>
    <div class="navbar navbar-expand-lg navbar-light bg-light">
       <div class="container">


           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse" id="navbarNav">
            
               <ul class="navbar-nav">
                <li class="text-warning bg-dark">Ezra's Django Home</li>
                   <li class="nav-item"><a class="nav-link" href="{% url "index" %}">Home</a></li>
                   <li class="nav-item"><a class="nav-link" href="{% url "admin:index" %}">Admin</a></li>
                   <li class="nav-item"><a class="nav-link" href="{% url "basic_app:register" %}">Register</a></li>
                   <li class="nav-item"><a class="nav-link" href="{% url "basic_app:other" %}">Other</a></li>
               
                    {% if user.is_authenticated %}
                      <li><a class='nav-link' href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
                    {% endif %}
               
                  </ul>
           </div>
       </div>
   </div>

    <div class="container">

        {% block body_block %}

        {% endblock %}
    </div>

  </body>
</html>

My_Django/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% load my_extras %}
  {% block body_block %}
    <h1>Welocme to INDEX</h1>
    <h2>This is index.html</h2>
    <h1>{{text|cut:'Hello'}}</h1>
    <h1>{{number|add:"99"}}</h1>
    {% endblock %}

    {% block body_block_1 %}
    <div class="jumbotron">
      <h1>Ezra's Django Website</h1>
      <h3>Developer: Ezra Lin</h3>
      <h3>LinkedIn:<a href="https://www.linkedin.com/in/ji-yanglin/">LinkedIn</a></h3>
    </div>
    {% endblock %}

My_Django/learning_templates/templates/basic_app/index2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : Cerulean
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20131223

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>test2.html</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial" rel="stylesheet" />
<link href="default.css" rel="stylesheet" type="text/css" media="all" />
<link href="fonts.css" rel="stylesheet" type="text/css" media="all" />

<!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->

</head>
<body>
<div id="header-wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><span class="icon icon-cog"></span><a href="#">Cerulean</a></h1>
			<div id="menu">
				<ul>
					<li class="current_page_item"><a href="#" accesskey="1" title="">Homepage</a></li>
					<li><a href="#" accesskey="2" title="">Our Clients</a></li>
					<li><a href="#" accesskey="3" title="">About Us</a></li>
					<li><a href="#" accesskey="4" title="">Careers</a></li>
					<li><a href="#" accesskey="5" title="">Contact Us</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<div id="page-wrapper">
	<div id="page" class="container">
		<div class="title">
			<h2>Welcome to our website</h2>
		</div>
		<p>This is <strong>Cerulean</strong>, a free, fully standards-compliant CSS template designed by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>. The photos in this template are from <a href="http://fotogrph.com/"> Fotogrph</a>. This free template is released under the <a href="http://templated.co/license">Creative Commons Attribution</a> license, so you're pretty much free to do whatever you want with it (even use it commercially) provided you give us credit for it. Have fun :) </p>
	</div>
</div>
<div class="wrapper">
	<div id="three-column" class="container">
		<div><span class="arrow-down"></span></div>
		<div id="tbox1">
			<div class="title">
				<h2>Maecenas luctus</h2>
			</div>
			<p>Nullam non wisi a sem semper eleifend. Donec mattis libero eget urna. Duis pretium velit ac suscipit mauris. Proin eu wisi suscipit nulla suscipit interdum.</p>
			<a href="#" class="button">Learn More</a> </div>
		<div id="tbox2">
			<div class="title">
				<h2>Integer gravida</h2>
			</div>
			<p>Proin eu wisi suscipit nulla suscipit interdum. Nullam non wisi a sem semper suscipit eleifend. Donec mattis libero eget urna. Duis  velit ac mauris.</p>
			<a href="#" class="button">Learn More</a> </div>
		<div id="tbox3">
			<div class="title">
				<h2>Praesent mauris</h2>
			</div>
			<p>Donec mattis libero eget urna. Duis pretium velit ac mauris. Proin eu wisi suscipit nulla suscipit interdum. Nullam non wisi a sem suscipit  eleifend.</p>
			<a href="#" class="button">Learn More</a> </div>
	</div>
	<div id="portfolio" class="container">
		<div class="column1">
			<div class="box"> <a href="#"><img src="images/scr01.jpg" alt="" class="image image-full" /></a>
				<h3>Vestibulum venenatis</h3>
				<p>Fermentum nibh augue praesent a lacus at urna congue rutrum.</p>
				<a href="#" class="button button-small">Etiam posuere</a> </div>
		</div>

		<div class="column3">
			<div class="box"> <a href="#"><img src="images/scr03.jpg" alt="" class="image image-full" /></a>
				<h3>Donec dictum metus</h3>
				<p>Vivamus fermentum nibh in augue praesent urna congue rutrum.</p>
				<a href="#" class="button button-small">Etiam posuere</a> </div>
		</div>
		<div class="column4">
			<div class="box"> <a href="#"><img src="images/scr04.jpg" alt="" class="image image-full" /></a>
				<h3>Mauris vulputate dolor</h3>
				<p>Rutrum fermentum nibh in augue praesent urna congue rutrum.</p>
				<a href="#" class="button button-small">Etiam posuere</a> </div>
		</div>
	</div>
</div>
<div id="wrapper2">
	<div id="tools">
		<div class="title">
			<h2>Vivamus fermentum nibh</h2>
		</div>
		<ul class="tools">
			<li><a href="#" class="icon icon-legal"></a></li>
			<li><a href="#" class="icon icon-random"></a></li>
			<li><a href="#" class="icon icon-key"></a></li>
			<li><a href="#" class="icon icon-wrench"></a></li>
			<li><a href="#" class="icon icon-cut"></a></li>
			<li><a href="#" class="icon icon-filter"></a></li>
			<li><a href="#" class="icon icon-lock"></a></li>
		</ul>

	</div>
</div>
<div id="copyright" class="container">
	<p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
		<ul class="contact">
			<li><a href="#" class="icon icon-twitter"><span>Twitter</span></a></li>
			<li><a href="#" class="icon icon-facebook"><span></span></a></li>
			<li><a href="#" class="icon icon-dribbble"><span>Pinterest</span></a></li>
			<li><a href="#" class="icon icon-tumblr"><span>Google+</span></a></li>
			<li><a href="#" class="icon icon-rss"><span>Pinterest</span></a></li>
		</ul>
</div>
</body>
</html>

My_Django/learning_templates/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block%}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" name="" value="Login">
    </form>



</div>

{% endblock %}

My_Django/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
  {% block body_block %}
    <h1>Welocme to OTHER</h1>
    <h2>This is exmaple of template inheritance</h2>

    {% endblock %}

My_Django/learning_templates/templates/basic_app/registeration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
  {% block body_block %}
  
    <div class=jumbotron>
      <h1>Test Register</h1>
      {% if registered %}
      <h1>Thank you for Register</h1> 
      {% else %}
      <h1>Register Here</h1>
      <h3>Fill out the form</h3>
          <form enctype="multipart/form-data" method="post" >
              {% csrf_token %}
              {{ user_form.as_p}}
              {{ profile_form.as_p }}
              <input type="submit" name="" value="Register">
            </form>
      {% endif %}
    </div>
  {% endblock %}

My_Django/learning_templates/templates/basic_app/registration.html
{% extends "basic_app/base.html"%}
{% load staticfiles %}
{% block body_block %}
  <div class=jumbotron>
    {% if registered %}
    <h1>Thank you for Register</h1> 
    {% else %}
    <h1>Register Here</h1>
    <h3>
        <h1>Fill out the form</h1>
        <form method="post" enctype="multi-part/form-data">
            {% csrf_token %}
            {{ user_form.as_p}}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    </h3>
    {% endif %}
  </div>
{% endblock %}

My_Django/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Relative</title>
  </head>
  <body>
    <h1>Welocme to RELATIVE_URL_TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">The admin page</a>
    <a href="{% url 'index' %}">The index page</a>
  </body>

</html>